import pandas as pd
from icecream import ic

# ori = pd.read_csv("data_analysis/df_paper_pc2s_year_filtered.tsv")
# ori = ori.groupby(["patent"]).first().reset_index()
# ori = ori.drop_duplicates()
# ic(ori["patent"].count())
# nr = pd.read_csv("data_analysis_no_researcher/patent_id_no_researcher.csv")
# nr["patent"] = nr["patent"].astype(str)
# nr = nr.groupby(["patent"]).first().reset_index()
# nr = ori.merge(nr, left_on='patent', right_on='patent')
# nr = nr.drop_duplicates()
# ic(nr["patent"].count())
# ns = pd.read_csv("data_analysis_non_self_cite/non_self_cite_patent_mag.tsv")
# ns = ori.merge(ns, left_on=['magid', 'patent'], right_on=['magid', 'patent'])
# ns = ns.groupby(['magid', 'patent']).first().reset_index()
# # ns = ns.groupby(["patent"]).first().reset_index()
# ic(ns["patent"].count())


paper_pd = pd.read_csv("data_analysis/df_paper_year_filtered.tsv")
paper_pd = paper_pd[(paper_pd["year"] >= 1980) & (paper_pd["year"] <= 2018)].drop_duplicates()
paper_pd = paper_pd.groupby(["paper_id"]).first().reset_index()
ic(paper_pd["paper_id"].count())
ic(paper_pd[paper_pd["conf_id"]==1163450153]["paper_id"].count())
ic(paper_pd[paper_pd["conf_id"]==1195049314]["paper_id"].count())
ic(paper_pd[paper_pd["conf_id"]==1166315290]["paper_id"].count())
ic(paper_pd[paper_pd["conf_id"]==1171345118]["paper_id"].count())

citation_pd = pd.read_csv("data_analysis/df_paper_pc2s_year_filtered.tsv")
citation_pd = citation_pd[(citation_pd["year"] >= 1980) & (citation_pd["year"] <= 2018)].drop_duplicates()
citation_pd = citation_pd.groupby(["magid", "patent"]).first().reset_index()
ic(len(citation_pd))
ic(len(citation_pd[citation_pd["conf_id"]==1163450153]))
ic(len(citation_pd[citation_pd["conf_id"]==1195049314]))
ic(len(citation_pd[citation_pd["conf_id"]==1166315290]))
ic(len(citation_pd[citation_pd["conf_id"]==1171345118]))